spring:
  profiles:
    active: dev


---
spring:
  profiles: dev
  application:
    name: server
server:
  port: 8010


---
spring:
  profiles: test
  application:
    name: test
server:
  port: 8888
